Models/Data/Client.cs
using System;
using System.Collections.Generic;

namespace btp.Models.Data;

public partial class Client
{
    public int Idclient { get; set; }

    public string? Numero { get; set; }

    public virtual ICollection<Devi> Devis { get; } = new List<Devi>();
}

Models/Functions/Client.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace btp.Models.Data
{
    public partial class Client
    {
        public static bool ISNumberValidFormat(string numero){
            // oe miatomboka amin'ny 0 ireo de 7 chiffres ny apres 
            bool regerx = Regex.IsMatch(numero,@"^(033|034`|038)\d\d{7}$");
            return regerx;
        }
        public static Client LogIn(BtpContext context, string numero)
        {
            Client? client = context.Clients
                                    .Where(c => c.Numero == numero)
                                    .FirstOrDefault();
            if (client == null)
            {
                Client d = new Client();
                d.Numero=numero;
                context.Clients.Add(d);
                context.SaveChanges();
                client=d;
            }
            return client;
        }
        public static List<Devi> GetPagined(BtpContext context,int idclient,int pageslide,int number){

            List<Devi> devis = context.Devis
                                .Where(d=>d.Idclient==idclient)
                                .Include(d=>d.IdtypemaisonNavigation)
                                .Include(d=>d.IdtypefinitionNavigation)
                                .Skip((pageslide - 1) * number)
                                .Take(number)
                                .ToList();
                                return devis;
        }
        public static double GetTotalPages(BtpContext context,int idclient,int number){
                           double d =  context.Devis
                                .Where(d=>d.Idclient==idclient)
                                .ToList().Count;
                                return (int)Math.Ceiling((double)d / number);
        }
    }
}

Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using btp.Models.Data;
using btp.Models.includes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Rotativa.AspNetCore;
namespace btp.Controllers
{
    [TypeFilter(typeof(SessionClientFilter))]
    public class ClientController : Controller
    {
        private readonly BtpContext _context;

        public ClientController(BtpContext _context)
        {
            this._context = _context;
        }
        public IActionResult Index(int? pageslide)
        {
                if(pageslide==null){
                    pageslide=1;
                }
                int a_afficher = 3;
                var retour = new{
                    Data = TypeMaison.GetPagined(_context, (int)pageslide,a_afficher),
                    TotalPage = TypeMaison.GetTotalPages(_context,a_afficher),
                    CurrentPage = (int)pageslide
                };
            return View(retour);
        }
        public IActionResult ConsultationDevis(int idtypemaison,int idfinition,DateOnly datedebuttravaux){
            try{
                int idclient = (int)HttpContext.Session.GetInt32("idclient");
            Devi d = Devi.GetWithoutException(_context,idtypemaison,idfinition,datedebuttravaux,idclient);
            var retour = new{
                Devi = d,
                String = JsonConvert.SerializeObject(d)
            };
            return  View(retour);
            }catch(Exception e){
                TempData["data"] = e.Message;
                TempData["idfinition"]=idfinition;
               Int32.Parse(TempData["idfinition"].ToString());
                TempData["date"] = datedebuttravaux.ToString();
                return RedirectToAction("Finitions","Client",new{id=idtypemaison});
            }   
        }
        public IActionResult DevisRequest(){
            return RedirectToAction("Index","Client");
        }
        public IActionResult Finitions(string id){
            Console.WriteLine("IDDDD = "+id); 

            int selected =Int32.Parse(id); 
            var retour = new{
                Finitions = _context.TypeFinitions.ToList(),
                Id = selected
            };
            return View(retour);
        }
        public IActionResult Confirmer(string data ){
           Devi consultation = JsonConvert.DeserializeObject<Devi>(data);
            Devi.Insert(_context,consultation);
            return RedirectToAction("All","Client");
        }
        public IActionResult All(int? pageslide){
            if(pageslide==null){
                pageslide=1;
            }
            int idclient = (int)HttpContext.Session.GetInt32("idclient");
            int number = 5;
            var retour = new{
                Data = Client.GetPagined(_context,idclient, (int)pageslide,number),
                CurrentPage = pageslide,
                TotalPage = Client.GetTotalPages(_context,idclient,number)
            };
            return View(retour);
        }
        // le get total ity no ovaina rehefa tokony 
        public IActionResult ExporterPdf(int id){
            List<DetailDevi> devis =Devi.GetAllForDetails(_context,id);
            string request = "select * from paiement_devis where iddevis = "+id;
            Devi d = _context.Devis.Where(d=>d.Iddevis==id).Include(d=>d.IdtypefinitionNavigation)
                                                                .Include(d=>d.IdclientNavigation)
                                                                .Include(d=>d.IdtypemaisonNavigation)
                                                                
                                                            .FirstOrDefault();
            List<PaiementDevi> paiements = _context.PaiementDevis
                                            .FromSqlRaw(request).ToList();
            double sommePayes = 0;
            foreach(PaiementDevi ds in paiements){
                sommePayes +=(double)ds.Montant;
            }
            var retour = new{
                MontantPayes = sommePayes,
                Paiements = paiements,
                Devi = devis,
                Total = Devi.GetTotal(_context,id),
                Data = d,
                MontantTotal = Devi.CalculMontantTotal(Devi.GetTotal(_context,id), (double)d.IdtypefinitionNavigation.AugmentationPourcentage)
            };
            return new ViewAsPdf("~/Views/Client/ExporterPdf.cshtml",retour){
                FileName = "devis_"+id+".pdf"
            };
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/PayerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using btp.Models.Data;
using btp.Models.includes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace btp.Controllers;
[TypeFilter(typeof(SessionClientFilter))]
public class PayerController : Controller
{
    private readonly BtpContext _context;

    public PayerController(BtpContext b)
    {
        _context = b;
    }

    public IActionResult Index(int id)
    {
        Devi d = _context.Devis.Where(d => d.Iddevis == id).FirstOrDefault();
        var retour = new
        {
            Devi = d,
            TotalPaye = d.GetResteAPayer(_context),
            CenseAPaye = d.GetResteCenseAPayer(_context)
        };
        return View(retour);
    }
    // TODO : mbola tsy vita ny mampiseho exception
    // public IActionResult AjouterPaiement(DateOnly date, double montant, int iddevis)
    // {
    //     // ato le tokony hisy verification zany
    //     try{
    //          PaiementDevi.Insert(_context, date, iddevis, montant);
        
    //     }catch(Exception e){
    //         TempData["montant"]=montant.ToString();
    //         TempData["date"]=date.ToString();
    //         TempData["log"]=e.Message;
    //     }
    //    return RedirectToAction("Index", "Payer", new { id = iddevis });
    // }
   
    public async Task<IActionResult>  AjouterPaiement(int iddevis, DateOnly date, double montant)
    {
        //  
        try{
            Console.WriteLine("ATOOO  AjouterPaiement");
            PaiementDevi.Insert(_context, date, iddevis, montant);
            //  "Payer/Index?id="+iddevis
            // return RedirectToAction("Index", "Payer", new { id = iddevis });
            return Json(new {url =Url.Action("Index","Client",new{id=iddevis})});
        }catch(Exception e){
            return Json(new{errors = e.Message} );
        }
        
    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View("Error!");
    }
}

Views/Client/All.cshtml
@{
    ViewData["Title"] = "Devis";
}
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="page-heading layout-horizontal">
                            <div class="header-top ">
                                <div class="container">
                                    <div class="header-top-right">
                                        <div class="card-header">
                                            <h4 class="card-title">Tableau</h4>
                                        </div>
                                     
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="">
                            <div class="table-responsive mb-4" style="margin: 2%;">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                             <th>Maison</th>
                                            <th>Finition</th>
                                            <th>Exporter</th>
                                            <th>Date debut travaux</th>
                                            <th>Date fin travaux</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in @Model.Data)
                                        {
                                            <tr>
                                                <td>@item.IdtypemaisonNavigation.NomMaison</td>
                                                <td>@item.IdtypefinitionNavigation.NomFinition</td>
                                                <td>@item.DateDebutTravaux.ToString("dd MMMM yyyy")</td>
                                               <td>@item.GetDateFin().ToString("dd MMMM yyyy")</td>
                                                <td>
                                                    <a class="btn icon icon-left btn-primary"
                                                    asp-action="Index" asp-controller="Payer" asp-route-id=@item.Iddevis
                                                    ><i
                                                            class="bi bi-cash-stack"></i>Payer</a>
                                                    <a class="btn icon icon-left btn-primary"
                                                    asp-action="ExporterPdf" asp-controller="Client" asp-route-id=@item.Iddevis
                                                    ><i
                                                            class="bi bi-file-earmark-pdf-fill"></i>Pdf</a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <div class="row">
                                <nav aria-label="Page navigation example">
                                <ul class="pagination pagination-primary justify-content-end">
                                    @if(Model.CurrentPage>1){
                                         <li class="page-item">
                                        <a class="page-link"  tabindex="-1" aria-disabled="true"  asp-action="Index" asp-controller="Client" asp-route-pageslide=@(Model.CurrentPage-1)><span
                                                aria-hidden="true"><i class="bi bi-chevron-left"></i></span></a>
                                    </li>
                                    }
                                    @for(int i=0;i<@Model.TotalPage;i++){
                                        if(i+1==Model.CurrentPage){
                                            <li class="page-item active"><a class="page-link" asp-action="Index" asp-controller="Client" asp-route-pageslide=@(i+1)>@(i+1)</a></li>
                                        }else{
                                             <li class="page-item"><a class="page-link" asp-action="Index" asp-controller="Client" asp-route-pageslide=@(i+1)>@(i+1)</a></li>
                                        }
                                    }
                                    @if(Model.CurrentPage<Model.TotalPage){
                                        <li class="page-item">
                                        <a class="page-link" 
                                        asp-action="Index" asp-controller="Client" asp-route-pageslide=@(Model.CurrentPage+1)
                                        >
                                            <span aria-hidden="true"><i class="bi bi-chevron-right"></i></span>
                                        </a>
                                    </li>
                                    }
                                    
                                </ul>
                            </nav>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Client/ConsultationDevis.cshtml
@using btp.Models.includes
@{
    ViewData["Title"] = "Consultation d'un devis";
}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Devis
        </div>
    </div>
    <div class="card-content">
        <div class="table-responsive mb-4" style="margin: 2%;">
            <table class="table table-borderless ">
                <thead>
                    <tr>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Client </td>
                        <td>@Model.Devi.IdclientNavigation.Numero</td>
                    </tr>
                    <tr>
                        <td>Type de maison</td>
                        <td>@Model.Devi.IdtypemaisonNavigation.NomMaison</td>
                    </tr>
                    <tr>
                        <td>Type de finition</td>
                        <td>@Model.Devi.IdtypefinitionNavigation.NomFinition (@Model.Devi.IdtypefinitionNavigation.AugmentationPourcentage %)</td>
                    </tr>
                    <tr>
                        <td>Montant travaux</td>
                        <td>Ar @SessionHelper.GetFormatted(Model.Devi.MontantTotalTravaux)</td>
                    </tr>
                    <tr>
                        <td>Montant total+finition</td>
                        <td>Ar @SessionHelper.GetFormatted(Model.Devi.MontantTotal)</td>
                    </tr>
                </tbody>
            </table>
        </div>
        @{
            @* var data = JSON.stringify(Model); *@
        }
        <div class="card-footer">
            <a class="btn btn-primary btn-block" asp-controller="Client" asp-action="Confirmer"
                asp-route-data=@Model.String>Suite</a>
        </div>
    </div>
</div>

Views/Client/ExporterPdf.cshtml
@using btp.Models.includes
@{
    ViewData["Title"] = "Home Page";
    Layout=null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/assets/compiled/css/app.css">
<link rel="stylesheet" href="~/assets/compiled/css/app-dark.css">
    <title>Document</title>
</head>
<style>
    .sous-titre{
        text-transform: uppercase;
    }
    .titre{
        font-weight: bold;
         text-transform: uppercase;
    }
</style>
<body>
    <section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h2>Devis  du client : @Model.Data.IdclientNavigation.Numero</h2>
                        <h3>Lieu : @Model.Data.Lieu</h3>
                        <h3>Maison : @Model.Data.IdtypemaisonNavigation.NomMaison</h3>
                        <p>Finition : @Model.Data.IdtypefinitionNavigation.NomFinition</p>
                </div>
                </div>
                
                <div class="card-content">
                    <div class="row">
                        <div class="">
                            <div class="table-responsive mb-4" style="margin: 2%;">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>DESIGNATION</th>
                                            <th>U</th>
                                            <th>Q</th>
                                            <th>PU</th>
                                            <th>TOTAL</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        
                                            @foreach(var detail in Model.Devi){
                                                    <tr>
                                                        <td class="text-bold-500">@detail.IdtravauxNavigation.Numero </td>
                                                        <td>@detail.IdtravauxNavigation.Designation</td>
                                                        <td>@detail.IdtravauxNavigation.IduniteNavigation.NomUnite</td>
                                                        <td>@detail.Quantite</td>
                                                        <td>@SessionHelper.GetFormatted(detail.Pu)</td>
                                                        <td>@SessionHelper.GetFormatted(detail.Total)</td>
                                                    </tr>
                                            }
                                            <tr id="total">
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td class="sous-titre">TOTAL TRAVAUX </td>
                                                <td class="text-bold-500">@SessionHelper.GetFormatted(Model.Total)</td>
                                            </tr>
                                             <tr id="total">
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td class="sous-titre">TOTAL AVEC FINITION </td>
                                                <td class="text-bold-500">@SessionHelper.GetFormatted(Model.MontantTotal)</td>
                                            </tr>
                                    </tbody>
                                </table>
                            </div>
                            

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
 <section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h2>Paiements </h2>
                        <p></p>
                </div>
                </div>
                
                <div class="card-content">
                    <div class="row">
                        <div class="">
                            <div class="table-responsive mb-4" style="margin: 2%;">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Date</th>
                                            <th>Ref Paiement</th>
                                            <th>Montant</th>
                                           
                                        </tr>
                                    </thead>
                                    <tbody>
                                        
                                            @foreach(var detail in Model.Paiements){
                                                    <tr>
                                                        <td class="text-bold-500">@detail.DatePrevue.ToString("dd MMMM yyyy") </td>
                                                        <td>@detail.RefPaiement</td>
                                                        <td>@SessionHelper.GetFormatted(detail.Montant)</td>
                                                    </tr>
                                            }
                                            <tr id="total">
                                                <td></td>
                                                <td class="sous-titre">TOTAL PAYEES </td>
                                                <td class="text-bold-500">@SessionHelper.GetFormatted(Model.MontantPayes)</td>
                                            </tr>
                                            
                                    </tbody>
                                </table>
                            </div>
                            

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>
 

Views/Client/Finitions.cshtml
@{
    ViewData["Title"] = "Finitions";
}
 <section id="basic-horizontal-layouts">
        <div class="placed-center">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Demander un devis : type de finition </h4>
                        
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form class="form form-horizontal" asp-action="ConsultationDevis" asp-controller="Client" method="post" >
                                <input type="hidden" name="idtypemaison" value="@Model.Id">
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <label for="first-name-horizontal">Type de finition</label>
                                        </div>
                                        <fieldset class="col-md-9 form-group">
                                            <select class="form-select" id="basicSelect" name="idfinition">
                                            @foreach (var s in Model.Finitions)
                                            {
                                                if(TempData["idfinition"]!=null && Int32.Parse(TempData["idfinition"].ToString())==s.Idtypefinition){
                                                        <option value="@s.Idtypefinition" selected>@s.NomFinition</option>
                                                }else{
                                                        <option value="@s.Idtypefinition">@s.NomFinition</option>
                                                }
                                                
                                            }
                                        </select>
                                        </fieldset>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-3">
                                            <label for="first-name-horizontal">Date debut des travaux</label>
                                        </div>
                                        <fieldset class="col-md-9 form-group">
                                            @if(TempData["date"]!=null){
                                                 <input type="text" name="datedebuttravaux" class="form-control" value="@TempData["date"]">
                                            }else{
                                                 <input type="date" name="datedebuttravaux" class="form-control">
                                            }
                                          
                                        </fieldset>
                                    </div>
                                    @if(TempData["data"]!=null){
                                        <div class="alert alert-danger"><i class="bi bi-exclamation-circle"></i> 
                                        @TempData["data"]
                                        </div>
                                    }
                                    <div class="col-sm-12 d-flex justify-content-end">
                                        <button type="submit" class="btn btn-primary me-1 mb-1 mt-4">Demander le devis</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

Views/Client/Index.cshtml
@{
    ViewData["Title"] = "Devis";
}
<div class="card">
    <div class="card-header">
        <div class="card-title">Demander un devis : type de maison </div>
    </div>
    <div class="card-content">
        <section class="section">
            <div class="row">
                <nav aria-label="Page navigation example">
                    <ul class="pagination pagination-primary justify-content-end">
                        @if (Model.CurrentPage > 1)
                        {
                            <li class="page-item">
                                <a class="page-link" tabindex="-1" aria-disabled="true" asp-action="Index"
                                    asp-controller="Client" asp-route-pageslide=@(Model.CurrentPage-1)><span
                                        aria-hidden="true"><i class="bi bi-chevron-left"></i></span></a>
                            </li>
                        }
                        @for (int i = 0; i < @Model.TotalPage; i++)
                        {
                            if (i + 1 == Model.CurrentPage)
                            {
                                <li class="page-item active"><a class="page-link" asp-action="Index" asp-controller="Client"
                                        asp-route-pageslide=@(i+1)>@(i + 1)</a></li>
                            }
                            else
                            {
                                <li class="page-item"><a class="page-link" asp-action="Index" asp-controller="Client"
                                        asp-route-pageslide=@(i+1)>@(i + 1)</a></li>
                            }
                        }
                        @if (Model.CurrentPage < Model.TotalPage)
                        {
                            <li class="page-item">
                                <a class="page-link" asp-action="Index" asp-controller="Client"
                                    asp-route-pageslide=@(Model.CurrentPage+1)>
                                    <span aria-hidden="true"><i class="bi bi-chevron-right"></i></span>
                                </a>
                            </li>
                        }

                    </ul>
                </nav>
            </div>

            <div class="row">
                <div class="col-11 offset-md-1">
                    <div class="pricing">
                        <div class="row align-items-center">
                            <form asp-controller="Client" asp-action="Finitions">
                                @foreach (var type in Model.Data)
                                {
                                    <div class="col-md-4 px-0">
                                        <div class="card">
                                            <div class="card-header text-center">
                                                <h4 class="card-title">@type.NomMaison</h4>
                                                <p class="text-center">@type.Descri</p>
                                            </div>
                                            <h4 class="price" style="margin-left: 2%;">Ar @type.formattedPrix</h4>
                                            @* <ul>
                                        <li><i class="bi bi-check-circle"></i></li>

                                        </ul> *@
                                            <div class="card-footer">

                                                <label for="">Choix</label>
                                                <input type="radio" name="id" value="@type.Idtypemaison">


                                            </div>
                                        </div>
                                    </div>
                                }
                                <div class="col-sm-12 d-flex justify-content-end">
                                    <button type="submit" class="btn btn-primary me-1 mb-1 mt-4">Suite</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

</div>